var env = process.env.NODE_ENV || 'development',
	resolve = require('path').resolve,
	cfg={};
cfg.port=80;
cfg.public=resolve(__dirname, '../../public');
cfg.views = resolve(__dirname, '../views');
cfg.streamApiConfig=["pb54b2anwcwtc2pmgh35agqe", "cETzTbGba4"];
cfg.dbConnection = 'mongodb://128.199.59.208:27017/uboxie';
cfg.cookieSecret='x40gjmlgsd';
module.exports=cfg;