module.exports={
	initialize:function(socket,sio){
		socket.on('songAdded',this.testEvent);
		socket.on('songChanged',this.testChEvent);
	},
	testEvent:function(msg){
		console.log(msg);
	},
	testChEvent:function(msg2){
		console.log('Changed');
		console.log(msg2);
	}
};